//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


public class EventName
{
    public const string u14testEvent = "u14testEvent";
    public const string u14testEvent2 = "u14testEvent2";
    public const string Drag_Begin = "Drag_Begin";
    public const string Drag_Move = "Drag_Move";
    public const string Drag_End = "Drag_End";
    public const string OnClickDown = "OnClickDown";
    public const string OnClickUp = "OnClickUp";
    public const string OnClickSuccess = "OnClickSuccess";
    public const string ProgressLevelCompleted = "ProgressLevelCompleted";
}
