//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoGenerateScriptSpace
{
    using System;
    using UnityEngine;
    
    
    [UnityEngine.SerializeField()]
    public class ExampleClass
    {
        
        public string str;
        
        public ExampleClass()
        {
        }
        
        // this is Str
        public string Str
        {
            get
            {
                return this.str;
            }
            set
            {
                this.str = value;
            }
        }
        
        public int Function(int number)
        {
 return number+1; 
        }
    }
}
