//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


public class ResName
{
    public const string prefab_Prefab_Cube_aaa = "Assets/Game/Prefab/Cube_aaa.prefab";
    public const string prefab_Prefab_Cube_bbb = "Assets/Game/Prefab/Cube_bbb.prefab";
    public const string playable_Timeline_环节1 = "Assets/Game/Timeline/环节1.playable";
}
